version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: n+qB39R9myZaMoWw4SG9Ra1VuUX96YcCMByW43v/Xuu768TpI8uJ5RY07s0oQIly
  skip_symbols: true
  artifact: '**\*.nupkg'
- provider: GitHub
  tag: CommandLine.AutoParser v$(appveyor_build_version)
  release: CommandLine.AutoParser v$(appveyor_build_version)
  auth_token:
    secure: 6hoZSmZskXUrehWMvL3i+FwSfZr+rMKwOxdIG2usuVOG5zUhXQ/Hcq/TzNqUigfF
  artifact: '**\*.nupkg'
