version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: detailed
deploy:
- provider: NuGet
  api_key:
    secure: F/AkZSLJHX8tWvRwFal7sgeOrkS9g0v2RtxxZd/Aqi6mRc9xq7xBEM9EOdlV86ni
  skip_symbols: false
- provider: GitHub
  auth_token:
    secure: QeUb3wjlvP0bht90xWcoRLcGA5GI6YXvv4CfXUgV/Oh3OJuLQHZ8VtD9c9FEwZqB
  artifact: /.*\.nupkg/
